-- AlterTable
ALTER TABLE "user_profiles" ADD COLUMN     "alcohol" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "averageCycleLength" INTEGER DEFAULT 28,
ADD COLUMN     "bloodGroup" TEXT,
ADD COLUMN     "bloodPressure" TEXT,
ADD COLUMN     "bmi" DOUBLE PRECISION,
ADD COLUMN     "childrenCount" INTEGER,
ADD COLUMN     "completionPercentage" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "complications" TEXT,
ADD COLUMN     "deficiencies" TEXT,
ADD COLUMN     "dependentsCount" INTEGER,
ADD COLUMN     "dietaryPreference" TEXT,
ADD COLUMN     "dietaryRestrictions" TEXT,
ADD COLUMN     "doctorName" TEXT,
ADD COLUMN     "exerciseHabits" TEXT,
ADD COLUMN     "expectedDueDate" TIMESTAMP(3),
ADD COLUMN     "familyHistory" TEXT,
ADD COLUMN     "favoriteFoods" TEXT,
ADD COLUMN     "heightCm" DOUBLE PRECISION,
ADD COLUMN     "hospital" TEXT,
ADD COLUMN     "maritalStatus" TEXT,
ADD COLUMN     "miscarriages" INTEGER DEFAULT 0,
ADD COLUMN     "notificationTime" TEXT,
ADD COLUMN     "pastPregnancies" INTEGER DEFAULT 0,
ADD COLUMN     "pregnancyType" TEXT,
ADD COLUMN     "primaryCaregiverContact" TEXT,
ADD COLUMN     "profileCompleted" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "sleepHours" DOUBLE PRECISION,
ADD COLUMN     "sleepQuality" TEXT,
ADD COLUMN     "smoking" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "spouseBloodGroup" TEXT,
ADD COLUMN     "spouseName" TEXT,
ADD COLUMN     "spousePhone" TEXT,
ADD COLUMN     "stressLevel" TEXT,
ADD COLUMN     "sugarLevel" TEXT,
ADD COLUMN     "supplements" TEXT,
ADD COLUMN     "supportPreferences" TEXT,
ADD COLUMN     "trimester" INTEGER,
ADD COLUMN     "waterIntakeLiters" DOUBLE PRECISION,
ADD COLUMN     "weightKg" DOUBLE PRECISION;
